server:
  port: 1300
  servlet:
    context-path: /tasty-town

spring:
  datasource:
    url: jdbc:mysql://localhost/tasty-town
    username: root
    password: root2004

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
